api/urls.py
from rest_framework import routers
from django.urls import path, include
from . import views

app_name = "api"
urlpatterns = [
    path(
        "categories/", views.CategoryListAPIView.as_view(), name="CategoryListAPIView"
    ),
    path(
        "categories/<int:pk>/",
        views.CategoryDetailAPIView.as_view(),
        name="CategoryDetailAPIView",
    ),
    path("products/", views.ProductAPIView.as_view(), name="ProductAPIView"),
]

app/urls.py
from django.conf import settings
from django.conf.urls.static import static

from . import views
from django.urls import path, include, reverse_lazy
from django.contrib.auth import views as auth_views

app_name = "app"
urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("<int:pk>/", views.DetailView.as_view(), name="detail"),
    path("signup/", views.signup, name="signup"),
    path(
        "login/",
        auth_views.LoginView.as_view(template_name="app/layout/login.html"),
        name="login",
    ),
    path(
        "logout/",
        auth_views.LogoutView.as_view(next_page=reverse_lazy("app:index")),
        name="logout",
    ),
    path("profile/", views.profile, name="profile"),
    path("update-profile/", views.update_profile, name="update_profile"),
    path("cart/", views.cart, name="cart"),
    path("add-to-cart/<int:product_id>/", views.add_to_cart, name="add_to_cart"),
    path(
        "update-item-cart/",
        views.update_item_cart,
        name="update_item_cart",
    ),
    path("checkout/", views.checkout, name="checkout"),
    path("order/", views.order, name="update_status_order"),
    path("order/<int:pk>", views.order, name="order_detail"),
    path("search", views.search, name="search"),
    path("tinymce/", include("tinymce.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django_banhang/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("app.urls")),
    path("api/", include("api.urls")),
]

app/templates/app/layout/footer.html
<div class=" about-introduce" style="background: #f5f5f5;">
    <div class="row">
        <div class="col-md">
            <div class="list-social m-5">
                <a href=""><i class="bi bi-facebook me-3"></i></a>
                <a href=""><i class="bi bi-youtube me-3"></i></a>
                <a href=""><i class="bi bi-twitter me-3"></i></a>
                <a href=""><i class="bi bi-instagram"></i></a>

            </div>
        </div>
        <div class="col-md">
            <h5 style="margin-top: 15px; font-style: bold;">Nhận tin mới từ Pandora </h5>
            <p>Đăng kí ngay để nhận thông tin mới nhất về khuyến mãi, sự kiện, offer... từ Pandora.</p>
            <input type="email" class="form-email" style="border: #000 solid 1px; width: 80%" id="exampleFormControlInput1" placeholder="Nhập email của bạn">
            <button class="bg-dark" style="width:50px; height:40px"><i class="bi bi-chevron-right text-light" ></i></button>
        </div>

    </div>
</div>

<footer class="pt-5" style="background: #f5f5f5;width: 100%;">
	<div class="container pt-3">
        <div class="row">
            <div class="col-md mt-2">
                <h1 class="text-footer">Giới thiệu</h1>
                <ul class="list-unstyled">
                    <li><a href="">Về Pandora</a></li>
                    <li><a href="">Câu chuyện Pandora</a></li>
                    <li><a href="">Về Tập Đoàn Norbreeze</a></li>
                    <li><a href="">Liên hệ</a></li>
                </ul>
            </div>
            <div class="col-md mt-2">
                <h1 class="text-footer">Khám phá Pandora</h1>
                <ul class="list-unstyled">
                    <li><a href="">Charms</a></li>
                    <li><a href="">Vòng tay</a></li>
                    <li><a href="">Hoa tai</a></li>
                    <li><a href="">Dây chuyền</a></li>
                    <li><a href="">Nhẫn</a></li>
                    <li><a href="">Khuyến mãi</a></li>
                    <li><a href="">Deal</a></li>
                </ul>
            </div>
            <div class="col-md mt-2">
                <h1 class="text-footer">Điều khoản và dịch vụ</h1>
                <ul class="list-unstyled">
                    <li><a href="">Câu hỏi thường gặp</a></li>
                    <li><a href="">Chính sách bảo mật</a></li>
                    <li><a href="">Chính sách thanh toán</a></li>
                    <li><a href="">Chính sách giao nhận</a></li>
                    <li><a href="">Chính sách đổi hàng</a></li>
                    <li><a href="">Chính sách bảo quản</a></li>
                </ul>
            </div>
            <div class="col-md mt-2">
                <h1 class="text-footer">Hệ thống cửa hàng</h1>
                <ul class="list-unstyled">
                    <li><a href="">Hồ Chí Minh</a></li>
                    <li><a href="">Hà Nội</a></li>
                    <li><a href="">Hệ thống Pandora toàn quốc</a></li>
                </ul>
            </div>
            <div class="col-md mt-2">
                <h1 class="text-footer">Giao hàng</h1>
                <ul class="list-unstyled">
                <li><a href="">VNPost</a></li>
                    <li><a href="">Nhất tín Logistics</a></li>
                </ul>
            </div>
        </div>
    </div>
</footer>

    <div class="" style="background: #f5f5f5;">
        <div class=" list-footer me-5 ">
            <div class="ft-last col-md-6">
                <p style="margin-top: 15px; margin-left: 130px; font-size: 15px;">© Pandora Jewelry, LLC. All rights reserved. </p>
            </div>
            <div class="ft-bct col-md-6 me-5">
                <img class="me-5" src="" alt="">
            </div>
        </div>
    </div>

app/templates/app/layout/header.html
{% load static %}
    <!DOCTYPE html>
    <html>

    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <meta name="viewport" content="width=device-width">
        <title>Pandora Việt Nam</title>
        <link rel="shortcut icon" href="//theme.hstatic.net/200000103143/1000942575/14/favicon.png?v=1433"
              type="image/png">
        <!-- CSS only -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
              integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
              crossorigin="anonymous">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css">
        <link rel="stylesheet"
              href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <link rel="stylesheet" type="text/css" href="{% static 'app/css/style.css' %}">

app/templates/app/layout/login.html
{% extends 'app/layout/master.html' %}

{% load static %}
{% block css %}
    <link rel="stylesheet" href="{% static 'app/css/login.css' %}">
{% endblock %}
{% block content %}
    <section style="background-image: url({{ '' }});">
        <div class="container py-5 ">
            <div class="row d-flex justify-content-center align-items-center mt-5 mb-5">
                <div class="col-md-12 col-lg-5 col-xl-5 mb-5 bg-light"
                     style="border-radius: 8px; box-shadow: 0 4px 12px #00000026;">
                    <form class="form-signin text-center mb-5" method="post">
                        {% csrf_token %}
                        <h1 class="titleLogin mt-3 pb-3">Đăng nhập</h1>
                        <div class="form-outline mb-4">
                            <label for="username">{{ form.username.label_tag }}</label>
                            {{ form.username }}
                        </div>

                        <div class="form-outline mb-2">
                            <label for="password">{{ form.password.label_tag }}</label>
                            {{ form.password }}
                        </div>
                        <div class=" d-flex mt-3 mb-3" style="display: inline;">
                            <a class="text-primary-50 me-1" href="" style="font-weight: 600; font-size: 17px;">Quên mật
                                khẩu</a>Hoặc
                            <a class="text-primary-50 ms-1" href="{% url 'app:signup' %}"
                               style="  font-weight: 600; font-size: 17px;">Đăng ký?</a>
                        </div>

                        <small style="color:red;">
                            {% if error_message %}{{ error_message }}{% endif %}
                        </small>
                        <input type="hidden" name="next" value="/">
                    
                        <button class="btn-signin glow-on-hover btn-lg bg-dark" name="btnSignin" type="submit">Đăng
                            nhập
                        </button>

                    </form>
                    <input id="infor" hidden value="<?php echo $_SESSION['infor'] ?? ''; unset($_SESSION['infor']) ?>">
                </div>
            </div>
        </div>
    </section>
{% endblock %}
{% block js %}
    <script src="https://code.jquery.com/jquery-3.6.0.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
            crossorigin="anonymous"></script>
    {#    <script src="./assets/js/sweetalert2.all.min.js"></script>#}
    <script src="https://code.jquery.com/ui/1.13.1/jquery-ui.js"></script>
    {#<script>#}
    {#    $(document).ready(function (){#}
    {#        if ($("#infor").val() !== '') {#}
    {#            Swal.fire(#}
    {#                {#}
    {#                    title: 'Thông báo!',#}
    {#                    text: $("#infor").val(),#}
    {#                    icon: 'info',#}
    {#                    confirmButtonText: 'OK'#}
    {#                }#}
    {#            )#}
    {#        }#}
    {#    })#}
    {#</script>#}
    <script src="{% static 'app/js/app.js' %}"></script>
{% endblock %}

app/templates/app/layout/master.html
{% include 'app/layout/header.html' %}
{% block css %} {% endblock %}
</head>
<body>
{% include 'app/layout/navbar.html' %}

<div class="new-item container">
    {% block content %}{% endblock content %}
</div>

{% include 'app/layout/footer.html' %}
<script src="https://code.jquery.com/jquery-3.7.0.min.js"
        integrity="sha256-2Pmvv0kuTBOenSvLm6bvfBSSHrUJ+3A7x6P5Ebd07/g=" crossorigin="anonymous"></script>
<script type="text/javascript" src="https://code.jquery.com/jquery-migrate-1.2.1.min.js"></script>
<script src="https://code.jquery.com/ui/1.13.1/jquery-ui.js"></script>
<script>
    $(document).ready(function () {
        $("#search")
            .autocomplete({
                source: "{% url 'app:search' %}",
            })
            .autocomplete("instance")._renderItem = function (ul, item) {
             let product_id = item.id
             let url = "{% url 'app:detail' 0 %}".replace('0', product_id)
             let image_url = item.image
                image_url = '/media/' + image_url
            return $("<li class='sub-search-item'>")
                .append(
                    `<a href='${url}' class='sub-search-link'>
                <img class='sub-search-link__img' src='${image_url}' alt=''>
                <h5 class='sub-search-link__name'>
                  ${item.name}
                </h5>
                <span class='sub-search-link__price'>
                ${item.price}&#8363
                </span>
              </a>`
                )
                .appendTo(ul);
        };
        $(".sub-menu").parent("li").addClass("has-child");

    });
</script>
{% block js %} {% endblock %}
</body>
</html>

app/templates/app/layout/navbar.html
<header class="medium-header fixed-top">
    <div id="title-header" class="title-header mb-3">
        <p>QUÀ TẶNG LÊN ĐẾN 3,000,000Đ</p>
        <button id="title" class="title">MUA NGAY</button>
        <button onclick="document.getElementById('title-header').style.display='none'" class="close">&times;
        </button>
    </div>

    <div class="site-header ">
        <div class="header-left col-md-6">
            <div id="mySidenav" class="sidenav">
                <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>

                <div class="drawer_header">
                    <a href="#"><img style="width:40%;height: 40%;"
                                     src="{{ '/media/app/images/Pandora_Logo_Blank.jpg' }}"></a>
                </div>

                <a href="{% url 'app:index' %}">Trang chủ</a>
                {% for category in category_list %}
                    <button class="dropdown-btn">{{ category.name }}
                        <i class="fa fa-caret-down"></i>
                    </button>
                    <div class="dropdown-container">
                        {% for child in category.category_children.all %}
                            <a href="">{{ child.name }}</a>
                        {% endfor %}
                    </div>
                {% endfor %}

                {% if not user.is_authenticated %}
                    <a href="{% url 'app:login' %}">
                        <i class="bi bi-people-fill" aria-hidden="true"></i>
                        Tài khoản
                    </a>
                {% else %}
                    <a href="./user_in4.php?id=<?= $each['id'] ?>">
                        <i class="bi bi-people-fill" aria-hidden="true"></i>
                        Chào , {{ user.username }}
                    </a>
                    <a href="{% url 'app:logout' %}">
                        <i class="bi bi-box-arrow-right" aria-hidden="true"></i>
                        Đăng Xuất
                    </a>
                {% endif %}

            </div>

            <div id="main">
                <span style="font-size:30px;cursor:pointer; color:#000" onclick="openNav()">&#9776; </span>
            </div>

            <div class="logo ms-5">
                <a href="{% url 'app:index' %}">
                    <img src="{{ '/media/app/images/Pandora_Logo_Blank.jpg' }}">
                </a>
            </div>
            <div class="search ms-5">
                <form action="./index.php" method="post" class="input-search ms-5" role="search">
                    <button type="submit" class="btn icon-fallback-text">
                        <i class="bi bi-search" aria-hidden="true"></i>
                    </button>
                    <input id="search" type="search" name="search"
                           value placeholder="Tìm sản phẩm..." class="input-field" aria-label="Tim kiem ..."
                           autocomplete="off" style="border: none;">
                </form>
                <div class="sub-search">
                    <ul class="sub-search-list">
                    </ul>
                </div>
            </div>

        </div>

        <div class="header-right">
            <ul class="list-item">
                <a class="item" href="#">
                    <i class="bi bi-geo-alt" aria-hidden="true"></i>
                </a>
                {% if  user.is_anonymous %}
                    <a class="item" href="{% url 'app:login' %}">
                        <i class="bi bi-person" aria-hidden="true"></i>
                    </a>
                {% else %}
                    <a class="item" href="{% url 'app:profile' %}">
                        <i class="bi bi-person" aria-hidden="true"></i>
                        Chào , {{ user.username }}
                    </a>
                    <a class="item" href="{% url 'app:logout' %}">
                        <i class="bi bi-box-arrow-right" aria-hidden="true"></i>
                        Đăng Xuất
                    </a>
                {% endif %}
                <a class="item" href="{% url 'app:cart' %}">
                    <div class="cart-total-price">
                        <i class="bi bi-bag" aria-hidden="true"></i>

                        {% if not user.is_authenticated %}
                            <span id="CartCount">0</span>
                        {% else %}
                            <span id="CartCount">{{ cart.get_total_item }}</span>
                        {% endif %}
                    </div>
                </a>
            </ul>
        </div>

    </div>
    <nav class="container">
        <ul id="main-menu">
            {% for category in category_list %}
                <li>
                    <a href="{% url 'app:index' %}?category={{ category.id }}">{{ category }}</a>
                    {% for child in category.category_children.all %}
                        <ul class="sub-menu">
                            <li>
                                <a href="{% url 'app:index' %}?category_child={{ child.id }}">{{ child.name }}</a>
                            </li>
                        </ul>
                    {% endfor %}

                </li>
            {% endfor %}
            <li><a href=".">Khuyến mãi</a></li>
            <li><a href=".">Tuyển dụng</a></li>
        </ul>
    </nav>
</header>
<div class="empty" style="height: 186px"></div>

app/templates/app/layout/signup.html
{% extends 'app/layout/master.html' %}
{% block content %}
    <section style="background-image: url({{ '' }});">
        <div class="container ">
            <div class="row d-flex justify-content-center mt-5 mb-5">
                <div class="col-md-12 col-lg-6 col-xl-6 mb-5 bg-light px-3"
                     style="border-radius: 8px; box-shadow: 0 4px 12px #00000026;">
                    <form class="form-signup text-center mb-5" id="form-signup" action="."
                          method="post">
                        <h1 class="titleSignup mt-3 pb-3">Đăng ký</h1>
                        {% csrf_token %}
                        {{ form.as_p }}
                        <small style="color:red;">
                            {% if error_message %}{{ error_message }}{% endif %}
                        </small>
                        <button class="btnSignup glow-on-hover btn-lg bg-dark" name="btnSignup" type="submit">Đăng ký
                        </button>
                    </form>
                    <div class=" d-flex mt-5 mb-3" style="display: inline;">
                        <a class="text-primary-50 me-1" href="{% url 'app:index' %}"
                           style="font-weight: 600; font-size: 17px;">
                            <i class="bi bi-arrow-left me-2 mt-1"></i>Quay về trang chủ</a>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}
{% block js %}
    <script src="https://code.jquery.com/jquery-3.6.0.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
            crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/ui/1.13.1/jquery-ui.js"></script>
{% endblock %}