api/urls.py
from rest_framework import routers
from django.urls import path, include
from . import views

app_name = "api"
urlpatterns = [
    path(
        "categories/", views.CategoryListAPIView.as_view(), name="CategoryListAPIView"
    ),
    path(
        "categories/<int:pk>/",
        views.CategoryDetailAPIView.as_view(),
        name="CategoryDetailAPIView",
    ),
    path("products/", views.ProductAPIView.as_view(), name="ProductAPIView"),
]

app/urls.py
from django.conf import settings
from django.conf.urls.static import static

from . import views
from django.urls import path, include, reverse_lazy
from django.contrib.auth import views as auth_views

app_name = "app"
urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("<int:pk>/", views.DetailView.as_view(), name="detail"),
    path("signup/", views.signup, name="signup"),
    path(
        "login/",
        auth_views.LoginView.as_view(template_name="app/layout/login.html"),
        name="login",
    ),
    path(
        "logout/",
        auth_views.LogoutView.as_view(next_page=reverse_lazy("app:index")),
        name="logout",
    ),
    path("profile/", views.profile, name="profile"),
    path("update-profile/", views.update_profile, name="update_profile"),
    path("cart/", views.cart, name="cart"),
    path("add-to-cart/<int:product_id>/", views.add_to_cart, name="add_to_cart"),
    path(
        "update-item-cart/",
        views.update_item_cart,
        name="update_item_cart",
    ),
    path("checkout/", views.checkout, name="checkout"),
    path("order/", views.order, name="update_status_order"),
    path("order/<int:pk>", views.order, name="order_detail"),
    path("search", views.search, name="search"),
    path("tinymce/", include("tinymce.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django_banhang/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("app.urls")),
    path("api/", include("api.urls")),
]

app/templates/app/cart.html
{% extends 'app/layout/master.html' %}
{% load humanize %}
{% load static %}
{% block css %}
    <link rel="stylesheet" type="text/css" href="{% static 'app/css/product.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'app/css/cart.css' %}">
{% endblock %}
{% block content %}
    <div class="mt-5 ms-5">
        <h4 class="ms-3">Giỏ Hàng của bạn</h4>
    </div>
    <div class="Pagecart container mb-4 ">
        <div class="row" id="form-checkout">
            {% csrf_token %}
            <div class="cart-content col-md-8">
                <div class="Empty_cart"
                        {% if cart_items %}
                     style="display: none"
                        {% else %}
                     style=" display: flex;
                        flex-direction: column;
                        align-items: center;"
                        {% endif %}
                >
                    <span class="cart-txt">Giỏ hàng đang trống</span>
                    <br><br>
                    <button class="bg-dark p-3">
                        <a class="cart-txt-he" href="{% url 'app:index' %}">
                            <i class="bi bi-cart me-2"></i> Tiếp tục mua sắm
                        </a>
                    </button>
                </div>
                <!--  -->
                <div
                        {% if cart_items %}
                            style="display:block;"

                        {% else %}
                            style="display:none;"
                        {% endif %}
                >
                    <table class="cart-table full">
                        <tbody>
                        {% for item in cart_items %}
                            <tr class="cart__row table__section">
                                <td class="item-img" data-label="Sản phẩm">
                                    <a href="{% url 'app:detail' item.product.id %}" class="cart__image">
                                        <img src="{{ item.product.image.url }}">
                                    </a>
                                </td>
                                <td class="item-content-text">
                                    <a href="{% url 'app:detail' item.product.id %}" class="item-text">
                                        {{ item.product.name }}
                                    </a>
                                    <div class="mt-2">
                                        Giá {{ item.product.price|intcomma }}&#8363
                                    </div>
                                    <div class="mt-2">
                                        <span style="font-weight: bold;"> Mã SP:</span>{{ item.product.id }}
                                    </div>
                                    <div class="mt-2">
                                        <span style="font-weight: bold;">Size:</span>{{ item.size.name }}
                                    </div>

                                    <div class="cart__remove"></div>
                                </td>
                                <td class="item-content-price" data-label="Đơn giá">
                                    <span class="item-price"></span>
                                </td>
                                <td class="item-amount" data-label="Số lượng">
                                    {% if item.product.quantity == 0 %}
                                        echo '<span style="color:red;">Hết hàng</span>';
                                    {% else %}
                                        <div class="product-quantitys">
                                            <div class="buttons_added">
                                                <button class="minus is-form update-item-cart"
                                                        data-type="minus"
                                                        data-id="{{ item.product_id }}"
                                                        data-cart="{{ item.cart_id }}"
                                                        data-size="{{ item.size.id }}"
                                                        type="button"
                                                >
                                                    -
                                                </button>
                                                <a class="input-qty">{{ item.quantity }}</a>
                                                <button class="plus is-form  update-item-cart"
                                                        data-type="plus"
                                                        data-id="{{ item.product_id }}"
                                                        data-cart="{{ item.cart_id }}"
                                                        data-size="{{ item.size.id }}"
                                                        type="button"
                                                >
                                                    +
                                                </button>
                                            </div>
                                        </div>
                                    {% endif %}
                                </td>
                                <td class="item-total-price" data-label="Tổng giá">
                                <span class="item-price">
                                    {{ item.get_total_price|intcomma }}&#8363
                                </span>
                                </td>
                                <td class="item-total-price" data-label="Tổng giá">
                                    {#                                    href="{% url 'app:remove_from_cart' item.product_id item.cart_id %}"#}
                                    <button class="btn-text update-item-cart" type="button"
                                            data-type="remove"
                                            data-id="{{ item.product_id }}"
                                            data-cart="{{ item.cart_id }}"
                                            data-size="{{ item.size.id }}"
                                    >
                                        <i style="color: #b17f99" class="bi bi-x-circle-fill"></i>
                                    </button>
                                </td>
                            </tr>
                        {% endfor %}

                        </tbody>
                    </table>
                    <div class="row total">
                        <div class="col-md pt-4">
                            <input class="mycheckbox m-3" type="checkbox" name="" id="" style="font-size: 20px;">Xuất
                            hóa đơn GTGT
                        </div>

                    </div>
                </div>
            </div>
            <div class="col-md-4 mt-2"
                    {% if not cart.get_total_item %}
                 style="display:none;"
                    {% else %}
                 style="display:block;"
                    {% endif %}
            >
                <div class="ms-4">
                    <span class="cartt__subtotal-title me-4">Tổng tiền</span>
                    <span class="cartt__total me-5">{{ cart.get_total_price| intcomma }}&#8363</span>
                </div>
                <div class="ms-4 mt-2" style="display: flex">
                <span class="cartt__subtotal-title me-3 mt-3"><input class="mycheckbox" id="checkout-check"
                                                                     type="checkbox"></span>
                    <span class="me-5">
                        <p>Khi bấm nút "Thanh toán" đồng nghĩa Khách hàng đã hiểu và đồng ý các Điều khoản dịch vụ của Pandora Việt Nam.</p>
                    </span>
                </div>
                <a href="{% url 'app:checkout' %}" class="btn-payment-text mt-2 ms-4 btn">
                    <span class="ps-5 pe-5 text-white">THANH TOÁN</span>
                </a>

                <div class="mt-3 ms-5" style="text-align: center;">
                    <a href="{% url 'app:index' %}" style="color: #d1b8c5">Tiếp tục mua sắm </a>
                </div>
                <div class="img-pay mt-3" style="display: flex; ">
                    <img class="ms-5" src="" alt="">
                </div>
            </div>
        </div>
    </div>

    <div class="container more_info p-3 mb-3">
        <div class="row">
            <div class="col-md ">
                <i class="bi bi-award"> Hàng chính hãng 100%</i>
            </div>
            <div class="col-md ">
                <i class="bi bi-truck"> Miễn phí giao hàng toàn quốc</i>
            </div>
            <div class="col-md ">
                <i class="bi bi-credit-card"> Mua trước trả sau với lãi suất 0%</i>
            </div>
        </div>
    </div>


    <div id="hotline">
        <a href="tel:0333135698" id="yBtn">
            <i class="bi bi-telephone-fill"></i>
        </a>
        <div class="text-quotes">
            <a href="tel:0333135698">0333135698</a>
        </div>
    </div>
{% endblock %}
{% block js %}
    <script src="https://code.jquery.com/ui/1.13.1/jquery-ui.js"></script>
    <script>
        $(document).ready(function () {
            const link = $('.btn-payment-text').attr("href");
            $(".btn-payment-text").removeAttr('href');
            $(".btn-payment-text").click(function () {
                if ($("#checkout-check").is(":checked")) {
                    $(".btn-payment-text").attr("href", link);
                } else {
                    alert("Bạn chưa đồng ý với điều khoản của Pandora Việt Nam. Vui lòng đồng ý để tiếp tục thanh toán");
                }
            });
            let btn_update_item = $(".update-item-cart");
            for (let i = 0; i < btn_update_item.length; i++) {
                btn_update_item.eq(i).click(function () {
                    let type = $(this).attr("data-type");
                    let id = $(this).attr("data-id");
                    let cart = $(this).attr("data-cart");
                    let size = $(this).attr("data-size");
                    let url = "{% url 'app:update_item_cart' %}";
                    $.ajax({
                        url: url,
                        type: "GET",
                        data: {
                            'cart_id': cart,
                            'product_id': id,
                            'type_update': type,
                            'size': size,
                        },
                        success: function (data) {
                            location.reload();
                        }
                    });
                });
            }
        });
    </script>
    <script src="{% static 'app/js/app.js' %}"></script>
    <script src="{% static 'app/js/product.js' %}"></script>
{% endblock %}

app/templates/app/checkout.html
{% load humanize %}
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Thanh toán đơn hàng-PANDORA</title>
    <link rel="shortcut icon" href="//theme.hstatic.net/200000103143/1000942575/14/favicon.png?v=1433" type="image/png">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'app/css/style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'app/css/confirminfo.css' %}">
</head>

<body>

<div class="main-container-header" style="background: #fafafa">
    <div class="row">
        <div class="col-md-6 py-4" style="background: #fff; border-right: solid 1px #ccc;">
            <div class="confirm-box">
                <div class="confirm-text mt-4">
                    <p>Pandora Việt Nam</p>
                </div>
            </div>
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb ms-5">
                    <li class="breadcrumb-item ms-5"><a href="{% url 'app:cart' %}">Giỏ hàng</a></li>
                    <li class="breadcrumb-item"><a href="#">Thông tin giao hàng</a></li>
                </ol>
            </nav>
            <form class="form-page " action="{% url 'app:checkout' %}" method="post">
                {% csrf_token %}
                <div class="page_container ">
                    <div class="main_content">
                        <div class="row user_infor">

                            <div class="col-md-2">
                                <img class="image-img" style="width: 100px; height: 100px;border-radius: 50%;"
                                     src=""/>
                            </div>
                            <div class="col-md-8 ms-3">
                                <div class="name mb-3 mt-3">
                                    {{ user.last_name }} {{ user.first_name }}({{ user.email }})
                                </div>
                                <a href="{% url 'app:logout' %}"><i class="bi bi-box-arrow-right"
                                                                    aria-hidden="true"></i>Đăng Xuất</a>
                            </div>
                        </div>

                        <div class="form_name">
                            <label for="">Họ và tên</label>
                            <input type="text" name="name_receiver" class="form-control"
                                   value="{{ user.last_name }} {{ user.first_name }}"
                                   style="width:80%" required>
                        </div>
                        <div class="form_address">
                            <label class="d-block" for="">Địa chỉ</label>
                            <select id="city-select" required>
                                <option value="">Chọn Tỉnh / Thành phố</option>
                            </select>
                            <select id="district-select" required>
                                <option value="">Chọn Quận / Huyện</option>
                            </select>
                            <select id="ward-select" required>
                                <option value="">Chọn Xã / Phường</option>
                            </select>
                            <label class="d-block mt-2" for="">Địa chỉ cụ thể</label>
                            <input type="text" name="address_receiver" class="form-control mb-2" style="width:80%"
                                   value="" required>
                            <input name="address_last" hidden id="address-min">
                        </div>


                        <div class="form_phone">
                            <label for="">Số điện thoại</label>
                            <input type="text" name="phone_receiver" class="form-control" value=""
                                   style="width:80%" required>
                        </div>

                    </div>
                    <h1 style="margin: 40px 0 20px 0; font-size: 25px; font-weight: bold;">Phương thức thanh toán</h1>
                    <div class="pay">
                        <div class="bybank mt-2">
                            <input type="radio" class="payment me-1 ms-3" name="payment" value="0"
                                   id="bank" autocomplete="off">
                            <label for="bank"><img src="img/paybyBank.svg" alt="" class="payby"> Chuyển khoản qua ngân
                                hàng</label>
                            <div class="infbank ">
                                <p>Quý khách vui lòng chuyển khoản theo thông tin sau:</p>
                                <p> - CONG TY TNHH THUONG MAI NCA (VN) </p>
                                <p> - NGÂN HÀNG TMCP KỸ THƯƠNG VIỆT NAM - TECHCOMBANK </p>
                                <p> - Số tài khoản: 19030734309076 (VND)</p>
                                <p> - Nội dung chuyển khoản: Thanh toán cho mã đơn hàng [Mã đơn hàng của bạn] Mã đơn
                                    hàng
                                    của bạn sẽ
                                    hiển thị khi bấm Hoàn tất đơn hàng</p>
                            </div>
                        </div>
                        <div class="shipcod mt-2">
                            <input type="radio" class="payment me-1 ms-3" name="payment" value="1"
                                   id="shipcod" autocomplete="off">
                            <label for="shipcod"><img src="img/cod.svg" alt="" class="payby"> Thanh toán khi giao hàng
                                (COD)</label>
                        </div>

                        <div class="vnpay mt-2">
                            <input type="radio" class="payment me-1 ms-3" name="payment" value="2"
                                   id="shipcod" autocomplete="off">
                            <label for="vnpay"><img src="img/vnpay_new.svg" alt="" class="payby"
                                                    style="width: 40px; height: 35px;"> Thẻ ATM/Visa/Master/JCB/QR Pay
                                qua
                                cổng VNPAY</label>
                        </div>

                        <div class="momo mt-2">
                            <input type="radio" class="payment me-1 ms-3" name="payment" value="3"
                                   id="momo" autocomplete="off">
                            <label for="momo"><img src="img/momo.svg" alt="" class="payby"
                                                   style="width: 40px; height: 35px;"> Ví Momo</label>
                        </div>

                        <div class="paypoo mt-2">
                            <input type="radio" class="payment me-1 ms-3" name="payment" value="4"
                                   id="momo" autocomplete="off">
                            <label for="paypoo"><img src="img/paypoo.svg" alt="" class="payby"
                                                     style="width: 40px; height: 35px;"> Trả góp qua ví Payoo</label>
                        </div>
                    </div>
                    <div class="col-md pt-4">
                            <p style="font-size: 17px;">Nhập ghi chú quà tặng hoặc hướng dẫn giao hàng đặc biệt dưới đây
                                (nếu có):</p>
                            <div class="form-field">
                                <textarea class="note" name="note" id="note" cols="30" rows="10"
                                          placeholder="Ghi chú: "></textarea>
                            </div>
                        </div>
                    <div class="btnup">
                        <a class="btnReturn" href="{% url 'app:cart' %}">Giỏ hàng</a>
                        <button type="submit" class="btnConfirm">Hoàn tất đơn hàng</button>
                    </div>
                </div>
            </form>

        </div>
        <div class="about-order col-md-6 pt-5">
            {% for item in cart_items %}
                <div class="row ms-3 pb-4">
                    <div class="col-md-8 " style="display: flex;">

                        <div class="item-img" data-label="Sản phẩm">
                            <a href="{% url 'app:detail' item.id %}" class="cart__image">
                                <img src="{{ item.product.image.url }}">
                            </a>
                        </div>
                        <div class="item-content-text">
                            <a href="{% url 'app:detail' item.id %}" class="item-text">
                                {{ item.product.name }}
                            </a>
                            <div class="inf-product mt-2">
                                {{ item.size.name }}/
                                {{ item.color }}/
                                {{ item.material }}/
                                {{ item.quantity }}
                            </div>
                        </div>
                    </div>
                    <div class="item-total-price col-md-3 ms-4 mt-3" data-label="Tổng giá">
                        <span class="item-price">
                            {{ item.get_total_price|intcomma }}&#8363
                        </span>
                    </div>
                </div>
            {% endfor %}

            <div class="row ms-3 pb-4 mt-4" style="border-bottom: #ccc 1px solid;">
                <div class="ms-2">
                        <span>
                            Tạm tính
                        </span>
                    <span class="item-price me-5" style="float: right; margin-right: 20px">
                                {{ cart.get_total_price|intcomma }}&#8363
                            </span>
                </div>
                <div class="ms-2 mt-2">
                    <span>Phí vận chuyển</span>
                    <span class="item-price me-5" style="float: right; margin-right: 20px">Miễn phí</span>
                </div>
            </div>
            <div class="row ms-3 pb-4 mt-4">
                <div class="ms-2">
                    <span>Tổng cộng</span>
                    <span class="item-price me-5" style="float: right; margin-right: 20px">
                        {{ cart.get_total_price|intcomma }}&#8363
                    </span>
                </div>
            </div>
        </div>
    </div>

    <div id="hotline">
        <a href="tel:0333135698" id="yBtn">
            <i class="bi bi-telephone-fill"></i>
        </a>
        <div class="text-quotes">
            <a href="tel:0333135698">0333135698</a>
        </div>
    </div>


</div>

<script src="https://code.jquery.com/jquery-3.7.0.min.js"
        integrity="sha256-2Pmvv0kuTBOenSvLm6bvfBSSHrUJ+3A7x6P5Ebd07/g=" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>
<script>
    $(document).ready(function () {
        $.getJSON('{% static 'app/hanh_chinh/tinh_tp.json' %}', function (data) {
            $.each(data, function (key, value) {
                $('#city-select').append('<option value="' + value.code + '">' + value.name + '</option>');
            })
        })

        $('#city-select').change(function () {
            var city = $(this).val();
            $.getJSON('{% static 'app/hanh_chinh/quan_huyen.json' %}', function (data) {
                $.each(data, function (key, value) {
                    if (value.parent_code === city) {
                        $('#district-select').append('<option value="' + value.code + '">' + value.name + '</option>');
                    }
                })
            })
        })

        $('#district-select').change(function () {
            var district = $(this).val();
            $.getJSON('{% static 'app/hanh_chinh/xa_phuong.json' %}', function (data) {
                $.each(data, function (key, value) {
                    if (value.parent_code === district) {
                        $('#ward-select').append('<option value="' + value.path_with_type + '">' + value.name + '</option>');
                    }
                })

                $('#district-select').change(function () {
                    var district = $(this).val();
                    $.getJSON('{% static 'app/hanh_chinh/xa_phuong.json' %}', function (data) {
                        $.each(data, function (key, value) {
                            if (value.parent_code === district) {
                                $('#ward-select').append('<option value="' + value.path_with_type + '">' + value.name + '</option>');
                            }
                        })
                    })
                });
                $('#ward-select').change(function () {
                    let ward = $(this).val();
                    $('#address-min').val(ward);
                });
            })
        });

        $('#ward-select').change(function () {
            let ward = $(this).val();
            $('#address-min').val(ward);
        });
    })
</script>
</body>
</html>

app/templates/app/index.html
{% extends 'app/layout/master.html' %}
{% load humanize %}
{% block content %}
    <ul class="products">
        {% for product in product_list %}
            <li>
                <a href="{% url 'app:detail' product.pk %}" class="product-item">
                    <div class="product-top">
                        <div class="product-thumb">
                            <img src="{{ product.image.url }}" alt="">
                        </div>
                    </div>
                    <div class="product-info">
                        <div class="product-cat">
                            <h1>{{ product.name }}</h1>
                        </div>
                        <p class="product-price">
                            {{ product.price|intcomma }}&#8363
                        </p>

                    </div>
                </a>
            </li>
        {% endfor %}
    </ul>
{% endblock %}

app/templates/app/update_profile.html
{% extends 'app/layout/master.html' %}
{% load static %}
{% block css %}
    <link rel="stylesheet" href="{% static 'app/css/update_profile.css' %}">
{% endblock %}
{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        <div class="page_container mb-3">
            <div class="main_content">
                <h2>THÔNG TIN TÀI KHOẢN</h2>
                <div class="form_name">
                    <label for="">Username:</label>
                    <input type="text" class=" m-1" value="{{ username }}">
                </div>
                <div class="form_name">
                    <label for="">Email:</label>
                    <input type="text" class=" ms-4" value="{{ email }}">
                </div>
                {{ form.as_p }}
                <small style="color:red;">
                    {% if error_message %}{{ error_message }}{% endif %}
                </small>
                <div class="btnup">
                    <button class="btnUpdate" name="btnUpdate" type="submit">Cập nhật</button>
                </div>
                <a href="{% url 'app:profile' %}" class="mt-3 d-flex align-items-center fs-5">
                    <i class="bi bi-arrow-left me-2"></i> <span>Quay lại</span>
                </a>
            </div>
        </div>
    </form>

    <div id="hotline">
        <a href="tel:0333135698" id="yBtn">
            <i class="bi bi-telephone-fill"></i>
        </a>
        <div class="text-quotes">
            <a href="tel:0333135698">0333135698</a>
        </div>
    </div>
{% endblock %}